services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-baltbereg
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/backup
      - mssql_data:/var/opt/mssql/data
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "SA", "-P", "${MSSQL_SA_PASSWORD}", "-Q", "SELECT 1", "-No"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: baltbereg-bot
    env_file: .env
    depends_on:
      mssql:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./data:/app/data

volumes:
  mssql_data:
